@host = http://localhost:3000

GET {{host}}/api/autores?page=2&limit=5

###
GET {{host}}/api/autores/5

###
GET {{host}}/api/posts

###
GET {{host}}/api/posts/3

###
GET {{host}}/api/posts/autor/2

###
POST {{host}}/api/posts
